# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "312"
license = "Apache"
licenselink = "https://github.com/swsmile/hugo-theme-312/blob/master/LICENSE"
description = "A cool blog theme for hugo"
homepage = "https://github.com/swsmile/hugo-theme-312"
tags = ["minimal", "responsive", "blog", "light", "clean", "search"]
features = ["site search", "responsive", "google analytics", "side bar"]
min_version = 0.10

[author]
name = "Shi Wei"
homepage = "https://github.com/zhaohuabing"

## If porting an existing theme
#[original]
#name = ""
#homepage = ""
